apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: genesis-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ErikNazaryan/AI-Help.git'
    targetRevision: main
    path: genesis-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

      