apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: default
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 5000 # 🔌 Flask հավելվածի պորտը
          protocol: TCP
        - name: metrics
          containerPort: 8000 # 📊 Prometheus մետրիկաների պորտը (HW35-ի պահանջը)
          protocol: TCP
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000 # 👈 Նայում է հիմնական Flask պորտին
          initialDelaySeconds: 30 # ⏱️ Երկարացրինք 30 վրկ, որ Python-ը հասցնի կպնել բազային
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-creds
              key: DB_PASSWORD
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-creds
              key: DB_USER