name: Project Genesis Modular Pipeline

on:
  push:
    branches:
      - main
      - gitops-release

jobs:
  call-shared-ci:
    uses: ErikNazaryan/ci-templates/.github/workflows/shared-pipeline.yml@main
    with:
      image_name: "eriknazaryan/genesis"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}